# Generated by Django 5.1.4 on 2025-06-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_city_user_full_name_remove_user_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
    ]
