# Generated by Django 5.2.5 on 2025-10-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_full_name_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
