# Generated by Django 5.2.5 on 2025-10-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='phone',
        ),
    ]
