# Generated by Django 5.1.4 on 2025-07-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_lesson_resource_remove_lesson_video_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
