# Generated by Django 5.1.4 on 2025-07-23 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_resource_name_video_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.FileField(blank=True, null=True, upload_to='files/lessons/tests', verbose_name='Test manbaa')),
            ],
            options={
                'verbose_name': 'Test manba',
                'verbose_name_plural': 'Test manbalar',
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Manba', 'verbose_name_plural': 'Manbalar'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='quiz',
        ),
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.test', verbose_name='Test'),
        ),
    ]
