# Generated by Django 5.1.4 on 2025-07-25 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_test_alter_resource_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
            preserve_default=False,
        ),
    ]
