# Generated by Django 5.1.4 on 2025-08-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lesson_test_test_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
