# Generated by Django 5.2.5 on 2025-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Ochiq dars'),
        ),
    ]
