# Generated by Django 5.2.5 on 2025-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_notification_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='courserating',
            name='created',
        ),
        migrations.RemoveField(
            model_name='courserating',
            name='score',
        ),
        migrations.RemoveField(
            model_name='courserating',
            name='updated',
        ),
        migrations.AddField(
            model_name='courserating',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
